# =========================================
# Production Profile (Rende r)
# =========================================
spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:postgres}?sslmode=require
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

# (optional) Keep logging if you want
logging.level.org.springframework.web=DEBUG
logging.level.com.ketrams.v2=DEBUG